// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Tarsasok_Asztali_Alkalmazas;
//
//    var authEmployee = AuthEmployee.FromJson(jsonString);

namespace Tarsasok_Asztali_Alkalmazas
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.Xml.Linq;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AuthEmployee
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("e_name")]
        public string EName { get; set; }

        [JsonProperty("e_email")]
        public string EEmail { get; set; }

        [JsonProperty("e_password")]
        public string EPassword { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        public override string ToString()
        {
            return EName;
        }
    }
    
    public partial class AuthEmployee
    {
        public static AuthEmployee FromJson(string json) => JsonConvert.DeserializeObject<AuthEmployee>(json, Tarsasok_Asztali_Alkalmazas.Converter.Settings);
    }

    public static class SerializeAuth
    {
        public static string ToJson(this AuthEmployee self) => JsonConvert.SerializeObject(self, Tarsasok_Asztali_Alkalmazas.Converter.Settings);
    }

    internal static class ConverterAuth
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
