// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Tarsasok_Asztali_Alkalmazas;
//
//    var employee = Employee.FromJson(jsonString);

namespace Tarsasok_Asztali_Alkalmazas
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;


    // Employee osztly, munkavállalók tulajdonságai
    public partial class Employee
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("e_name")]
        public string EName { get; set; }

        [JsonProperty("e_email")]
        public string EEmail { get; set; }

        [JsonProperty("e_password")]
        public string EPassword { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        // ToString() az objektum szöveges megjelenítésére
        public override string ToString()
        {
            return EName;
        }
    }

    public partial class Employee
    {
        public static Employee[] FromJson(string json) => JsonConvert.DeserializeObject<Employee[]>(json, Tarsasok_Asztali_Alkalmazas.Converter.Settings);
    }

    public static class SerializeEmployee
    {
        public static string ToJson(this Employee[] self) => JsonConvert.SerializeObject(self, Tarsasok_Asztali_Alkalmazas.Converter.Settings);
    }

    internal static class ConverterEmployee
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

